### ISSUE TITLE
Stop-execution Feature request 

### ISSUE THREAD

**Issue by jdvillal** [jbpita/ISII-WORKSHOPS-MI_FAMILIA#3]
**Is your feature request related to a problem? Please describe.**
There is not option in between data input to stop running the program. 

**Describe the solution you'd like**
I´d like an onption to stop running the program when the data input part of the program is running. So this could be implementing by stoping the program when the user input an speciphic letter.

**Describe alternatives you've considered**
The letter to stop running the program could be "q" stands for quit, or maybe "e" stands for exit.

**Additional context**

Of course is letter "q" or "e" is already been used to input any kind of data needed by the program this could change, as long as the program specifies wich letter to input in order to stop the program.

**Comment by jbpita** [comment]
Ok , let´s implement that option

**Comment by jbpita** [comment]
issue has been categorized

**Comment by jbpita** [comment]
@jdvillal will take this issue

**Comment by jdvillal** [comment]
The resources needed to implement this feature are:
Simple development hardware, no custom equipment required.
We will need to implement the feature by adding som functionality directly in the source code.
No database is needed for the implementation of this feature.
The main part of the software will be afected because the requested functionality will be implemented there.
@jdvillal

**Comment by jbpita** [comment]
Your request has been attended and resolved,
is in accordance with the new requirements implemented @jdvillal

**Comment by jdvillal** [comment]
I agree, thoose changes will work. Thanks!

**Comment by jdvillal** [comment]
The feature has been implemented.

https://github.com/jbpita/ISII-WORKSHOPS-MI_FAMILIA/blob/01099295502353c1434cc1d9b8c160e7b5544152/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L160-L176

**Comment by jdvillal** [comment]
The unit test of the new feature has passed without any issue.

![image](https://user-images.githubusercontent.com/57422146/213830744-fc93cdbe-910b-4352-937b-19f86af34860.png)

**Comment by jdvillal** [comment]
The acceptance test has passed without any issue. Attach result of the tests.

![image](https://user-images.githubusercontent.com/57422146/213831204-1df0cbb4-ed9a-47fb-8821-cd91f554d717.png)

**Comment by jdvillal** [comment]
@jdvillal @jbpita The solution has been accepted

**Comment by jdvillal** [comment]
The solution was implemented exactly as it was described when the issue was open. At any point in the input data process, the user can input the letter "q" and press enter in order to stop the execution of the program.

**Comment by jdvillal** [comment]
The new version of the software does work.

**Comment by jdvillal** [comment]
This issue can be closed now. @jdvillal @jbpita
